---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################  

# This playbook is responsible for configuring Apache modules.
# It performs the following tasks:
# 1. Sets the fact 'managed_modules' to the value of 'apache2_modules' variable.
# 2. Finds all the '*.load' files in the '/etc/apache2/mods-enabled' directory and stores the result in 'mods_enabled_contents' variable.
# 3. Disables unmanaged modules by using the 'community.general.apache2_module' module and the 'absent' state.
# 4. Enables managed modules by using the 'community.general.apache2_module' module and the 'present' state.
# 5. Notifies the 'Restart apache2' handler after disabling or enabling modules.

- set_fact:
    managed_modules: "{{ apache2_modules }}"
  register: managed_modules_state

- find:
    paths: /etc/apache2/mods-enabled
    patterns: '*.load'
    file_type: any 
  register: mods_enabled_contents

- name: Disable unmanaged modules
  community.general.apache2_module:
    state: absent
    name: "{{ item }}"
  loop: "{{ mods_enabled_contents.files | map(attribute='path') | map('basename') | map('splitext') | map('first') | list }}"
  when: item not in managed_modules
  notify: Restart apache2

- name: Enable managed modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop: "{{ apache2_modules }}"
  when: item in managed_modules
  notify: Restart apache2
