---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################  

# This task creates a default virtual host configuration file for Apache2.
# It uses the 'template' module to generate the configuration file from a Jinja2 template.
# The source template file is located at './templates/etc/apache2/default.conf.j2',
# and the destination file is '/etc/apache2/sites-available/{{ apache2_default_filename }}.conf'.
# The owner and group of the destination file are set to 'root', and the file permissions are set to '0644'.
# This task is conditional and will only run if the variable 'apache2_enable_default' is true.
# After the configuration file is created, it triggers the 'Reload apache2' handler.

- name: Create default vhost
  ansible.builtin.template:
    src: ./templates/etc/apache2/default.conf.j2
    dest: /etc/apache2/sites-available/{{ apache2_default_filename }}.conf
    owner: root
    group: root
    mode: '0644'
  when: apache2_enable_default
  notify: Reload apache2

# This task creates a symbolic link to the default virtual host configuration file.
# It uses the 'file' module with the 'state' parameter set to 'link'.
# The source file is '/etc/apache2/sites-available/{{ apache2_default_filename }}.conf',
# and the destination file is '/etc/apache2/sites-enabled/{{ apache2_default_filename }}.conf'.
# The owner and group of the destination file are set to 'root'.
# This task is conditional and will only run if the variable 'apache2_enable_default' is true.
# After the symbolic link is created, it triggers the 'Reload apache2' handler.

- name: Link default vhost
  ansible.builtin.file:
    src: /etc/apache2/sites-available/{{ apache2_default_filename }}.conf
    dest:  /etc/apache2/sites-enabled/{{ apache2_default_filename }}.conf
    owner: root
    group: root
    state: link
  when: apache2_enable_default
  notify: Reload apache2
