---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################  

# This task creates configuration files for Apache2 using templates and sets the appropriate permissions.
- name: Ensure {{ conf }}.conf is present
  ansible.builtin.template:
    src: ./templates/etc/apache2/conf/{{ conf }}.conf.j2
    dest: /etc/apache2/conf-available/{{ conf }}.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload apache2

# This task links the created configuration files and reloads Apache2.
- name: Link {{ conf }}.conf to conf-enabled
  ansible.builtin.file:
    src: /etc/apache2/conf-available/{{ conf }}.conf
    dest: /etc/apache2/conf-enabled/{{ conf }}.conf
    owner: root
    group: root
    state: link
  notify: Reload apache2
