---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
#########################################  

# This task creates vhost configuration files for Apache2.
- name: Ensure {{ vhost.name }}.conf is present
  ansible.builtin.template:
    src: ./templates/etc/apache2/vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ vhost.name }}.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload apache2

# This task links the vhost configuration files and reloads Apache2.
- name: Link {{ vhost.name }}.conf to sites-enabled
  ansible.builtin.file:
    src: /etc/apache2/sites-available/{{ vhost.name }}.conf
    dest: /etc/apache2/sites-enabled/{{ vhost.name }}.conf
    owner: root
    group: root
    state: link
  notify: Reload apache2
