---
#########################################
#            _             _ _          #
#           | |           (_) |         #
#           | | __ ___   ___| | __      #
#       _   | |/ _` \ \ / / | |/ /      #
#      | |__| | (_| |\ V /| |   <       #
#       \____/ \__,_| \_/ |_|_|\_\      #
#                                       #
######################################### 

# This playbook installs and configures Apache2 on the target servers.

- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
  # Update the repository cache to ensure the latest package information is available.

- name: Ensure {{ apache2_package }} version {{ apache2_version }} is installed
  ansible.builtin.apt:
    name: "{{ apache2_package }}"
    state: "{{ apache2_version }}"
  # Ensure that the specified version of the Apache2 package is installed on the servers.

- name: Ensure libapache2-mod-fcgid is installed
  ansible.builtin.apt:
    name: libapache2-mod-fcgid
    state: latest
  # Ensure that the latest version of the libapache2-mod-fcgid package is installed.

- name: Copy apache2.conf to servers
  ansible.builtin.template:
      src: ./templates/etc/apache2/apache2.conf.j2
      dest: /etc/apache2/apache2.conf
      owner: root
      group: root
      mode: '0644'
  notify:
    - Restart apache2
  # Copy the apache2.conf template file to the servers and set the appropriate permissions.
  # Notify the "Restart apache2" handler to restart the Apache2 service if the configuration file is changed.

- name: Allow http and https traffic through firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: 
    - http
    - https
  # Allow HTTP and HTTPS traffic through the firewalld service.
